/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gunday;


import java.awt.Color;
import java.io.File;
import static java.lang.Thread.sleep;
import javax.swing.JOptionPane;


/**
 *
 * @author Er. Ved Prakash Arya
 */
public class ShortCutVirus extends javax.swing.JFrame{
   
    /**
     * Creates new form ShortCutVirus
     */
    public ShortCutVirus() {
        
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        DriveValue = new javax.swing.JComboBox();
        Kill = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reload = new javax.swing.JButton();
        mszbox = new javax.swing.JLabel();
        V1 = new javax.swing.JRadioButton();
        V2 = new javax.swing.JRadioButton();
        V3 = new javax.swing.JRadioButton();
        V4 = new javax.swing.JRadioButton();
        V5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUNDAY");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 51, 255));

        DriveValue.setBackground(new java.awt.Color(204, 255, 102));
        DriveValue.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        DriveValue.setForeground(new java.awt.Color(0, 153, 0));
        DriveValue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Removable Drive", "C:", "D:", "E:", "F:", "G:", "H:", "I:", "J:", "K:", "L:", "M:" }));

        Kill.setBackground(new java.awt.Color(255, 255, 51));
        Kill.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        Kill.setForeground(new java.awt.Color(0, 0, 255));
        Kill.setText("Remove Virus");
        Kill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KillActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shortcut-virus.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reload.jpg"))); // NOI18N
        reload.setBorderPainted(false);
        reload.setContentAreaFilled(false);
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });

        mszbox.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        mszbox.setForeground(new java.awt.Color(255, 51, 204));
        mszbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        buttonGroup2.add(V1);
        V1.setForeground(new java.awt.Color(0, 0, 255));

        buttonGroup2.add(V2);

        buttonGroup2.add(V3);

        buttonGroup2.add(V4);

        buttonGroup2.add(V5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DriveValue, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(Kill))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addComponent(mszbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(V1)
                .addGap(18, 18, 18)
                .addComponent(V2)
                .addGap(18, 18, 18)
                .addComponent(V3)
                .addGap(18, 18, 18)
                .addComponent(V4)
                .addGap(18, 18, 18)
                .addComponent(V5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reload, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DriveValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(Kill, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mszbox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(V1)
                    .addComponent(V2)
                    .addComponent(V3)
                    .addComponent(V4)
                    .addComponent(V5))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(496, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        String drivevalue,selectedValue;
        
    private void KillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KillActionPerformed
        drivevalue =(String)DriveValue.getSelectedItem();
        //selectedValue=drivevalue+" /s";
        
         String Op[]={"YES","NO"};  
         if (drivevalue.equals("Select Removable Drive")){
                JOptionPane.showMessageDialog(null, "Not Selected Any Removable Drive");
            }
         else{
            int code=JOptionPane.showOptionDialog(null, "Are You Confirm!", null, 0, 1,null, Op, "");
            if(code==1){
                
            }
            else{
                Kill.setBackground(Color.GRAY);
                Kill.setEnabled(false);
                try {
                    Runtime.getRuntime().exec("cmd /c Attrib -h -r -s /s /d "+drivevalue+"\\*.*");
                     Thread clock;
                    clock = new Thread(){
                 
                 public void run(){
                    try{
                        File folder = new File(drivevalue+"\\");
                        File[] listOfFiles = folder.listFiles();
                        int v2=listOfFiles.length;
                        for (int i = 0; i < listOfFiles.length; i++) {
                           if (listOfFiles[i].isFile()) {
                               String name=listOfFiles[i].getName();
                              mszbox.setText("File:- " + listOfFiles[i].getName());
                               if(name.endsWith(".lnk")){
                                listOfFiles[i].delete();
                              }
                              scroll();
                              sleep(500);
                           }
                           else if (listOfFiles[i].isDirectory()) {
                                String name=listOfFiles[i].getName();
                                if(name.endsWith(".lnk")){
                                listOfFiles[i].delete();
                               
                              }
                              mszbox.setText("Directory:- " + listOfFiles[i].getName());
                             
                              scroll();
                              sleep(500);
                           }
                        }
                        JOptionPane.showMessageDialog(null, "Scan Completed\n\nVirus Removed!\n\n Drive is Fixed");
                       Kill.setEnabled(true);
                       Kill.setBackground(Color.yellow);
                       mszbox.setText("");
                       V1.setVisible(false);
                       V2.setVisible(false);
                       V3.setVisible(false);
                       V4.setVisible(false);
                       V5.setVisible(false);
                       
                       
                   }
                  catch(Exception ex){
                      JOptionPane.showMessageDialog(null, ex, "Warning!", JOptionPane.ERROR_MESSAGE);
                  }
                }
             };
                    clock.start();
                   
                }
                catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
        
            }
       
    }//GEN-LAST:event_KillActionPerformed
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                       V1.setVisible(false);
                       V2.setVisible(false);
                       V3.setVisible(false);
                       V4.setVisible(false);
                       V5.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
       String x[] = new String[2];
        
            main(x);
            this.setVisible(false);
    }//GEN-LAST:event_reloadActionPerformed
    int sc=1;
    void scroll(){
        V1.setVisible(true);
        V2.setVisible(true);
        V3.setVisible(true);
        V4.setVisible(true);
        V5.setVisible(true);
      if(V1.isSelected()){
          sc=1;
      }
      if(V2.isSelected()){
          sc=2;
      }
      if(V3.isSelected()){
          sc=3;
      }
      if(V4.isSelected()){
          sc=4;
      }
      if(V5.isSelected()){
          sc=5;
      }
      switch(sc){
          case 1:{
               V2.setSelected(true);
               V1.setSelected(false);
         }
                break;
          case 2:{
               V3.setSelected(true);
               V2.setSelected(false);
          }
              break;
          case 3:{
              V4.setSelected(true);
              V3.setSelected(false);
          }
              break;
          case 4:{
              V5.setSelected(true);
              V4.setSelected(false);
          }
              break;
          case 5:{
              V1.setSelected(true);
              V5.setSelected(false);
          }
              break;
      }
  }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortCutVirus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortCutVirus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortCutVirus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortCutVirus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShortCutVirus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DriveValue;
    private javax.swing.JButton Kill;
    private javax.swing.JRadioButton V1;
    private javax.swing.JRadioButton V2;
    private javax.swing.JRadioButton V3;
    private javax.swing.JRadioButton V4;
    private javax.swing.JRadioButton V5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mszbox;
    private javax.swing.JButton reload;
    // End of variables declaration//GEN-END:variables
}
